package com.HumanResourcesProject.enums;

public enum OperationType {

    //token için
    AUTHENTICATION_LOGIN,
    AUTHENTICATION_REGISTER,
    AUTHENTICATION_REFRESH_TOKEN,
    //personel için
    PERSONAL_CREATE,
    PERSONAL_UPDATE,
    PERSONAL_DELETE,
    PERSONAL_GET_BY_ID,
    PERSONAL_GET_ALL,
    PERSONAL_FILTER_BY_REGISTRATION_NO_AND_NAME,
    PERSONAL_SEARCH,
    PERSONAL_UPDATE_PHOTO,
    PERSONAL_COUNT_ACTIVE,
    PERSONAL_GET_ALL_ACTIVE,

    //envanter için
    INVENTORY_CREATE,
    INVENTORY_UPDATE,
    INVENTORY_DELETE,
    INVENTORY_GET_BY_ID,
    INVENTORY_LIST,
    INVENTORY_FILTER,

    //envanter tipi için
    INVENTORY_TYPE_CREATE,
    INVENTORY_TYPE_LIST,

    //zimmet için
    ASSIGNMENT_CREATE,
    ASSIGNMENT_UPDATE,
    ASSIGNMENT_DELETE,
    ASSIGNMENT_GET_BY_ID,
    ASSIGNMENT_LIST,
    ASSIGNMENT_LIST_BY_PERSONAL_ID,
    ASSIGNMENT_GET_ALL_ACTIVE,
    ASSIGNMENT_FILTER_BY_RETURNED_DATE_IS_NULL,

    //bildiirm için

    NOTIFICATION_SEND,
    NOTIFICATION_GET_BY_USER,
    NOTIFICATION_MARK_AS_READ,
    NOTIFICATION_LIST_ALL,
    NOTIFICATION_LIST_ALL_FOR_ADMIN,
    NOTIFICATON_LIST_UNREAD,
    NOTIFICATION_DELETE,


    //ortak işlemler

    SYSTEM_HEALTH_CHECK,
    UNKNOWN_OPERATION



}
