version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
  # ben hazırladım bu şekilde fakat volumes kısmına dikkat edin
  # app:
  #   build: .
  #   container_name: hr_app
  #   depends_on:
  #     - logstash
  #     - elasticsearch
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "bu iki çentik arasında " # buraya fotografların tutulacagı kısım gelecektir
  #   networks:
  #     - elk



networks:
  elk:
    driver: bridge