package com.HumanResourcesProject.exception;

import lombok.Getter;

@Getter
public enum MessageType {
    NO_RECORD_EXIST("1000","RECORD IS NOT EXIST"),
    NO_HTTP_EXIST("1001","HTTP IS NOT FOUND"),
    TOKEN_IS_EXPIRED("1002","TOKEN İS EXPİRED"),
    TOKEN_INVALID("1018","TOKEN INVALID"),
    USER_NOT_FOUND("1003","USER NOT FOUND"),
    USERNAME_OR_PASSWORD_INVALID("1004","USERNAME OR PASSWORD IS INVALID"),
    REFRESH_TOKEN_NOT_FOUND("1005","REFRESH TOKEN IS NOT FOUND"),
    REFRESH_TOKEN_IS_EXPIRED("1006","REFRES TOKEN IS EXPIRED"),
    USER_ALREADY_EXIST("1007","USER IS ALREADY EXIST"),
    PERSONAL_NOT_FOUND("1008","PERSONAL IS NOT FOUND"),
    INVENTORY_NOT_FOUND("1009","INVENTORY IS NOT FOUND"),
    INVENTORY_ASSIGNMENT_NOT_FOUND("1010","NO EMPLOYED INVENTORY FOUND"),
    INVENTORY_AND_PERSONAL_SAME_ASSIGNMENT("1011","PERSONAL AND INVENTORY ALREADY EXIST SAME ID"),
    INVENTORY_ALREADY_ASSIGNED("1012","INVENTORY ALREADY ASSIGNED BY A PERSONAL"),
    INVENTORY_NOT_ASSIGNED("1013","INVENTORY_NOT_ASSIGNED"),
    NOTIFICATION_NOT_FOUND("1014","NOTİFİCATİON İS NOT FOUND"),
    REGISTRATION_NO_IS_MONDATORY("1015","REGISTRATION NO IS MONDATORY"),
    REGISTRATION_NO_NOT_FOUND("1016","REGISTRATION NO IS NOT FOUND"),
    PERSONAL_NOT_LINKED("1017","PERSONAL IS NOT LINKED"),
    GENERAL_EXCEPTION("9999","GENERALLY PROBLEM");



    private String code;
    private String message;

    MessageType(String code, String message) {
        this.code = code;
        this.message = message;
    }
}
